### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_i18n#12]
Hi,

When I tried to install the package with `npm i lv_i18n -g` is got this error:
```
npm ERR! code E404
npm ERR! 404 Not Found: lv_i18n@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kisvegabor/.npm/_logs/2019-03-05T04_19_00_019Z-debug.log
```

The log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/kisvegabor/.nvm/versions/node/v11.2.0/bin/node',
1 verbose cli   '/home/kisvegabor/.nvm/versions/node/v11.2.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   'lv_i18n',
1 verbose cli   '-g' ]
2 info using npm@6.4.1
3 info using node@v11.2.0
4 verbose npm-session 87c124f9c609d5d5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/lv_i18n 916ms
8 silly fetchPackageMetaData error for lv_i18n@latest 404 Not Found: lv_i18n@latest
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 1079ms
11 verbose stack Error: 404 Not Found: lv_i18n@latest
11 verbose stack     at fetch.then.res (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at processImmediate (timers.js:632:19)
12 verbose cwd /home/kisvegabor/projects/littlevgl/i18n
13 verbose Linux 4.15.0-38-generic
14 verbose argv "/home/kisvegabor/.nvm/versions/node/v11.2.0/bin/node" "/home/kisvegabor/.nvm/versions/node/v11.2.0/bin/npm" "i" "lv_i18n" "-g"
15 verbose node v11.2.0
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: lv_i18n@latest
19 verbose exit [ 1, true ]
```

What am I doing wrong?

**Comment by puzrin** [comment]
It's not published in npm registry yet. Use `npm i littlevgl/lv_i18n -g` instead.

**Comment by kisvegabor** [comment]
It was working, thank you!

Extract still not working but I open a new sue for it.

**Comment by puzrin** [comment]
extract should provide details how to fix
